name: bluetooth_hfp
description: Windows Bluetooth headset with safe driver recovery and native audio.
publish_to: 'none'
version: 2.0.0+3

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
