# Compile the same catalog consumed by the privileged PowerShell controller.
file(READ "${CMAKE_CURRENT_LIST_DIR}/../tools/controller-profiles.json" catalog)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_LIST_DIR}/../tools/controller-profiles.json")
string(JSON schema GET "${catalog}" schemaVersion)
if(NOT schema EQUAL 1)
  message(FATAL_ERROR "Unsupported controller catalog")
endif()
string(JSON count LENGTH "${catalog}" profiles)
if(count LESS 1)
  message(FATAL_ERROR "Empty controller catalog")
endif()
math(EXPR last "${count} - 1")
set(entries "")
set(identities "")
foreach(i RANGE ${last})
  foreach(field id vid pid backend validation)
    string(JSON ${field} GET "${catalog}" profiles ${i} ${field})
  endforeach()
  if(NOT id MATCHES "^[a-z0-9-]+$" OR NOT vid MATCHES "^[0-9A-F][0-9A-F][0-9A-F][0-9A-F]$" OR NOT pid MATCHES "^[0-9A-F][0-9A-F][0-9A-F][0-9A-F]$")
    message(FATAL_ERROR "Malformed controller identity")
  endif()
  if(NOT backend STREQUAL "intel-legacy" OR NOT validation MATCHES "^(reference-tested|experimental)$")
    message(FATAL_ERROR "Unimplemented controller backend or validation level")
  endif()
  if("${vid}:${pid}" IN_LIST identities)
    message(FATAL_ERROR "Ambiguous controller profiles")
  endif()
  list(APPEND identities "${vid}:${pid}")
  # Experimental entries are discoverable but cannot reach transport or driver switching.
  if(validation STREQUAL "reference-tested")
    string(APPEND entries "{0x${vid}, 0x${pid}, HFP_BACKEND_INTEL_LEGACY, \"${id}\", L\"USB\\\\VID_${vid}&PID_${pid}\\\\\", \"usb#vid_${vid}&pid_${pid}#\"},\n")
  endif()
endforeach()
if(entries STREQUAL "")
  message(FATAL_ERROR "No enabled controller profiles")
endif()
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/generated/controller_profile_entries.inc" "${entries}")
configure_file("${CMAKE_CURRENT_LIST_DIR}/../bluetooth/controller_profiles.h" "${CMAKE_CURRENT_BINARY_DIR}/generated/controller_profiles.h" COPYONLY)
include_directories("${CMAKE_CURRENT_BINARY_DIR}/generated")
